import json

prefixes = [
    "Let's think about this step by step:",
    "Let's solve this systematically:",
    "Let's break this down into steps:",
    "Let me analyze this methodically:",
    "Here's my step-by-step reasoning:",
    "Let's approach this logically:",
    "Breaking this down systematically:",
    "Following a step-by-step approach:",
    "Let me reason through this carefully:",
    "Analyzing this in sequential steps:",
    "Let's work through this methodically:",
    "Taking this one step at a time:",
    "Let's examine this systematically:",
    "Walking through this step by step:",
    "Let's solve this through careful reasoning:",
    "Here's my structured analysis:",
    "Let me break this down logically:",
    "Approaching this systematically:",
    "Let's think through this methodically:",
    "Following a logical sequence of steps:",
    "Let's analyze this step by step:",
    "Here's my step-by-step analysis:",
    "Let me solve this systematically:",
    "Breaking this problem down:",
    "Let's reason about this carefully:",
    "Taking a structured approach:",
    "Let's examine this methodically:",
    "Here's my systematic solution:",
    "Let me think through this logically:",
    "Following these analytical steps:",
    "Let's solve this through clear steps:",
    "Here's my methodical approach:",
    "Let me break this down step by step:",
    "Analyzing this systematically:",
    "Let's work through this logically:",
    "Taking a step-by-step approach:",
    "Let's examine this carefully:",
    "Here's my logical analysis:",
    "Let me solve this methodically:",
    "Following these reasoning steps:",
    "Let's understand this step by step:",
    "Here's my detailed breakdown:",
    "Let me analyze this systematically:",
    "Breaking this into clear steps:",
    "Let's reason through this methodically:",
    "Taking a logical approach:",
    "Let's examine this step by step:",
    "Here's my systematic breakdown:",
    "Let me think about this carefully:",
    "Following this analytical process:",
    "Let's solve this step by step:",
    "Here's my careful analysis:",
    "Let me break this down methodically:",
    "Analyzing this logically:",
    "Let's work through this systematically:",
    "Taking these analytical steps:",
    "Let's examine this logically:",
    "Here's my step-by-step solution:",
    "Let me solve this carefully:",
    "Following this systematic approach:",
    "Let's understand this methodically:",
    "Here's my logical breakdown:",
    "Let me analyze this step by step:",
    "Breaking this down methodically:",
    "Let's reason about this systematically:",
    "Taking a methodical approach:",
    "Let's examine this analytically:",
    "Here's my careful breakdown:",
    "Let me think through this systematically:",
    "Following these logical steps:",
    "Let's solve this methodically:",
    "Here's my systematic analysis:",
    "Let me break this down carefully:",
    "Analyzing this step by step:",
    "Let's work through this carefully:",
    "Taking these methodical steps:",
    "Let's examine this systematically:",
    "Here's my analytical approach:",
    "Let me solve this logically:",
    "Following this step-by-step process:",
    "Let's understand this systematically:",
    "Here's my methodical breakdown:",
    "Let me analyze this logically:",
    "Breaking this down step by step:",
    "Let's reason through this systematically:",
    "Taking an analytical approach:",
    "Let's examine this methodically:",
    "Here's my logical solution:",
    "Let me think about this systematically:",
    "Following these methodical steps:",
    "Let's solve this analytically:",
    "Here's my step-by-step breakdown:",
    "Let me break this down systematically:",
    "Analyzing this methodically:",
    "Let's work through this logically:",
    "Taking these systematic steps:",
    "Let's examine this step by step:",
    "Here's my methodical solution:",
    "Let me solve this step by step:",
    "Following this logical approach:",
    "Let's understand this carefully:",
    "Here's my analytical breakdown:",
    "Let me analyze this methodically:"
]

# Write to JSONL file
with open('seed_prefixes.jsonl', 'w') as f:
    for prefix in prefixes:
        f.write(json.dumps({'prefix': prefix}) + '\n')

print(f"Created seed_prefixes.jsonl with {len(prefixes)} prefixes") 